# -*- coding: utf-8 -*-
"""Digit_recognization_continue.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgVTZw-yYys5aBnx_oHZRBpIgx5VIC8Q
"""

import pandas as pd
import numpy as np
from keras.layers import Conv2D , MaxPooling2D , Dense, Flatten , Input , Dropout
from keras.models import Sequential , Model
import keras
import tensorflow as tf
from PIL import Image
from keras.models import model_from_json
import os
from keras.preprocessing.image import ImageDataGenerator
from keras import utils as np_utils

json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model_digit.h5")
print("Loaded model from disk")
loaded_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

df = pd.read_csv('train.csv')
Y = np.asarray(df['label'])
#df1 = pd.read_csv('s1.csv')
#Y1 = np.asarray(df1['Label'])
Y = np.concatenate((Y, Y, Y, Y), axis=0)
Y = np.reshape(Y, (Y.shape[0], 1))
print(Y.shape)
df = df.drop(['label'], axis=1)

a = []
for x in range(784):
  a.append('pixel'+str(783-x))
b = []
for x in range(28):
  for y in range(28):
    b.append('pixel'+str(x*28 + 27-y))
c = []
for x in range(28):
  for y in range(28):
    c.append('pixel'+str((27-x)*28 + y))
df1 = df[a]
images = df.to_numpy()
#df2 = pd.read_csv('test.csv')
#im2 = df2.to_numpy()
imr = df1.to_numpy()
df2 = df[b]
df3 = df[c]
immx = df2.to_numpy()
immy = df3.to_numpy()
#print(im2.shape)
print(images.shape)
images = np.concatenate((images, imr, immx, immy), axis=0)
print(images.shape)
images = np.reshape(images, (images.shape[0], 28, 28, 1))
X = images
del images
#del im2
X = X/255.0
print(X.shape)
Y = np_utils.to_categorical(Y)
print(Y)

loaded_model.fit(X , Y , batch_size = 128 , epochs = 200 )

model_json = loaded_model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
loaded_model.save_weights("model_digit.h5")
print("Saved model to disk")

df1 = pd.read_csv('test.csv')
images = df1.to_numpy()
images = np.reshape(images, (images.shape[0], 28, 28, 1))
Xt = images
del images
Xt = Xt/255.0
print(Xt.shape)
Yt = loaded_model.predict(Xt)
Ya = []
for a in range(len(Yt)):
  mi=0
  mv=0
  for b in range(10):
    if(Yt[a][b]>mv):
      mv = Yt[a][b]
      mi=b
  Ya.append(mi)
print(Ya)
Ya = np.asarray(Ya)
df2 = pd.DataFrame(Ya)
df2 = df2.rename(index=str, columns={0:'Label'})
print(df2)
df2['ImageId'] = [(x+1) for x in range(Ya.shape[0])]
print(df2)
df2.to_csv('s1.csv')